### ISSUE TITLE
Room Tracking Bug

### ISSUE THREAD

**Issue by FyreByrns** [Dracentis/Monkland#1]
[consoleLog.zip](https://github.com/Dracentis/Monkland/files/4604436/consoleLog.zip)
[exceptionLog.txt](https://github.com/Dracentis/Monkland/files/4604433/exceptionLog.txt)

I was still able to move around the world, though I could no longer see the host

**Comment by Dracentis** [comment]
[exceptionLog.txt](https://github.com/Dracentis/Monkland/files/4604439/exceptionLog.txt)
[consoleLog.txt](https://github.com/Dracentis/Monkland/files/4604441/consoleLog.txt)

**Comment by Dracentis** [comment]
I've successfully repeated this bug and confirmed that it is caused by a problem with the room tracker.

**Comment by Dracentis** [comment]
[exceptionLog.txt](https://github.com/Dracentis/Monkland/files/4605747/exceptionLog.txt)

**Comment by Dracentis** [comment]
bug fixed in version 0.1.7
