### ISSUE TITLE
somethings wrong

### ISSUE THREAD

**Issue by Catbutother** [Dracentis/Monkland#10]
so, i was activating monkland in partiality and then error happened, the LOG.txt file have this: 

Checking if file is mod C:\GOG Games\rain world\Mods\Monkland.dll
Checking for modmeta at C:\GOG Games\rain world\Mods\Monkland.modMeta
Checking if file is mod C:\GOG Games\rain world\Mods\Monkland.modHash
Checking if file is mod C:\GOG Games\rain world\Mods\Monkland.modMeta
Loaded metadata for 1 mods
Run Game
Partiality+Monkland+
Patching Assembly-CSharp
MMEC:-1
MonoMod 18.6.0.33005
[MonoMod] Reading input file into module.
[MonoMod] [Main] Reading mods list from arguments.
[MonoMod] [ReadMod] Loading mod: C:\GOG Games\rain world\Mods\Monkland.dll
MonoMod.Utils.RelinkTargetNotFoundException: MonoMod cannot map dependency Monkland.dll -> ((Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null), (Assembly-CSharp-firstpass)) - not found
   ў MonoMod.MonoModder.DefaultMissingDependencyResolver(MonoModder mod, ModuleDefinition main, String name, String fullName)
   ў MonoMod.MonoModder.MapDependency(ModuleDefinition main, String name, String fullName, AssemblyNameReference depRef)
   ў MonoMod.MonoModder.MapDependency(ModuleDefinition main, AssemblyNameReference depRef)
   ў MonoMod.MonoModder.MapDependencies(ModuleDefinition main)
   ў MonoMod.MonoModder.MapDependencies()
   ў MonoMod.Program.Main(String[] args)

what can i do to fix this?
(i am playing on pirate GOG btw)

**Comment by Dracentis** [comment]
Unfortunately, Monkland uses Steam networking to communicate with other players and will not work without being signed into a Steam account.
