### ISSUE TITLE
When player 1 hits enemy with spear, player 2 freezes until the enemy is killed or if the spear is removed.

### ISSUE THREAD

**Issue by Yangjo** [Dracentis/Monkland#5]
I notice that enemies are not synced up in general with both non-hosts and hosts in a session. I believe that's because the mod isn't quite finished yet, as the implementation of enemy syncing isn't finished? 
This issue I'm reporting is correlated to this, a player and their world freezes up, but not their game. This happens whenever the other player in their session, if on their screen, attacks an enemy with a spear and sticks it in them. It happens regardless of being the host or non-host, it just doesn't happen to whoever attacks the enemy. So if the host attacks it, the non-host player will freeze. Alternatively, the non-host attacks and sticks a spear into an enemy, the host freezes up. This issue resolves whenever the enemy I believe is killed or the spear is taken out of them? Then the player can once again move.

My logs:
[consoleLog.txt](https://github.com/Dracentis/Monkland/files/4872924/consoleLog.txt)
[exceptionLog.txt](https://github.com/Dracentis/Monkland/files/4872925/exceptionLog.txt)

My friend's logs:
[exceptionLogHostFriend.txt](https://github.com/Dracentis/Monkland/files/4872919/exceptionLogHostFriend.txt)
[consoleLogHostFriend.txt](https://github.com/Dracentis/Monkland/files/4872920/consoleLogHostFriend.txt)

If you need more help to test, or need more info, I would be gladly willing.

**Comment by Dracentis** [comment]
Yes, none of the creatures other than slugcats are synced, as of this version of Monkland. However, this bug related to hitting a creature that is not synced is interesting and should be fixed. I will try to repeat it on my own.

**Comment by Yangjo** [comment]
https://youtu.be/WjoLWv_ukgo
This is the only video demonstration I have of it, I decided to record it when I had it happen a third time. Sadly, I do not show what my friend looks like on the off-screen. He would be frozen and stuck in place, but at least you hear me asking my friend repeatedly if he's frozen. He freezes whenever the lizard has the spear stuck in him. Then he gets un-frozen whenever I take the spear out of the lizard. It must correlate with the spear getting stuck in an enemy.

Non-Bug Suggestion Idea & Question: Any plans on adding this online multiplayer functionality to Arena? Also a post-death or sleep spectator camera to see what other players are doing? (as an option in the lobby)



### **Edit** 7/5/2020 3:02 PM UTC: 
[**Player 1 - Connected Player POV**: ](https://www.youtube.com/watch?v=8M2IqlSwpLE) Whenever the spear gets stuck in the first green lizard, my friend freezes. I take the spear out and he unfreezes. 
**_However_**, when I threw the same two spears repeatedly into a purple lizard until it died, my friend stayed frozen. Even when I took out all the spears. I can't tell for sure if the delayed response in the removal of the second spear, or if the repeated and multiple uses of spears, caused my friend to stay frozen.

[**Player 2 - Host POV**:](https://www.youtube.com/watch?v=4wxPuI9M3lY) My friend sees none of the enemies I'm fighting, and he freezes in accordance to when I stick the enemies on my screen with the spears. You can see that his game and world seem to be active, but he cannot move. His game is not frozen, just his character.
